---
#
# Core Informatics Freezer YAML configuration
#

# When assembling location names, include a delimiter if desired
# for example, F2S3R1D1B4 vs F2-S3-R1-D1-B4
name_delimiter: "-"

# Container levels to build
containers_to_use:
  - c1
  - c2
  - c3
  - c4
# Name and barcode of (parent) freezer
freezer: F2
barcode_freezer: FRZ2

# Container specifications
# Prefix and 'Starting index' needs to be looked up in C.I. LIMS via the
# Admin > Location > ENTITY_TYPE > List All. From there, find the
# appropriate values
c1:
  name_prefix: S
  name_starting_index: 1
  barcode_prefix: SHF
  barcode_starting_index: 13
  number_to_create: 1
c2:
  name_prefix: R
  name_starting_index: 1
  barcode_prefix: RCK
  barcode_starting_index: 56
  number_to_create: 3
c3:
  name_prefix: CL
  name_starting_index: 1
  barcode_prefix: SLC
  barcode_starting_index: 43
  number_to_create: 3
c4:
  name_prefix: RW
  name_starting_index: 1
  barcode_prefix: SLR
  barcode_starting_index: 295
  number_to_create: 7
...